apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: assignment
data:
  APP_MESSAGE: "Hello World from Kind Kubernetes"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "appdb"
  DB_USER: "appuser"
  POSTGRES_DB: "appdb"
  POSTGRES_USER: "appuser"
